# Generated by Django 2.1.1 on 2018-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180915_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeWordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.CharField(max_length=600, null=True)),
            ],
        ),
    ]
